version: '3.8'

services:
  chatbot-api:
    image: pratham0111/mutual-fund-chatbot:latest
    ports:
      - "8000:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8080
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped

  chatbot-ui:
    image: pratham0111/mutual-fund-chatbot-ui:latest
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_API_URL=http://chatbot-api:8080/query
    command: ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      - chatbot-api
    restart: unless-stopped

  ollama-api:
    image: pratham0111/mutual-fund-chatbot:latest
    ports:
      - "11434:11434"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "local_model_api:app", "--host", "0.0.0.0", "--port", "11434"]
    restart: unless-stopped 