apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutual-fund-chatbot-deployment
  labels:
    app: mutual-fund-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutual-fund-chatbot
  template:
    metadata:
      labels:
        app: mutual-fund-chatbot
    spec:
      containers:
      - name: chatbot-api-container
        # IMPORTANT: Replace this with your own image path after building and pushing
        image: your-dockerhub-username/mutual-fund-chatbot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30

apiVersion: v1
kind: Service
metadata:
  name: mutual-fund-chatbot-service
spec:
  selector:
    app: mutual-fund-chatbot
  ports:
    - protocol: TCP
      port: 80 # The port the service is exposed on
      targetPort: 8000 # The port the container is listening on
  # Use LoadBalancer to expose the service externally through a cloud provider's load balancer
  type: LoadBalancer

