apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-api
  labels:
    app: ollama-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-api
  template:
    metadata:
      labels:
        app: ollama-api
    spec:
      containers:
      - name: ollama-api
        image: pratham0111/mutual-fund-chatbot:latest  # Replace with actual image if different
        command: ["uvicorn", "local_model_api:app", "--host", "0.0.0.0", "--port", "11434"]
        ports:
        - containerPort: 11434
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: ollama-api
spec:
  selector:
    app: ollama-api
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP
