apiVersion: v1
kind: Service
metadata:
  name: mutual-fund-chatbot-service
spec:
  selector:
    app: mutual-fund-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080  # Exposes it on localhost:30080
  type: NodePort
